name: Convert index.htm to HTML5 and add styles.css

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout default branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write index.htm and styles.css
        run: |
          cat > index.htm <<'HTML_EOF'
<!doctype html>
<html lang="pt-PT">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Serviço de Patologia Clínica — CHUC</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="site-header" role="banner">
    <div class="container header-inner">
      <a href="index.htm" class="logo" aria-label="Página inicial CHUC">
        <img src="index_files/image2439.png" alt="Logótipo CHUC" width="140" height="79">
      </a>
      <nav class="main-nav" role="navigation" aria-label="Navegação principal">
        <ul>
          <li><a href="index_files/Page375.htm">Organização</a></li>
          <li><a href="index_files/Page451.htm">Contactos</a></li>
          <li><a href="index_files/Page527.htm">Lista de serviços</a></li>
          <li><a href="index_files/Page618.htm">Lista de análises</a></li>
          <li><a href="index_files/Page700.htm">Lista de projectos</a></li>
          <li><a href="index_files/Page13415.htm">Colheitas</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <main class="site-main container" role="main">
    <aside class="sidebar" role="complementary" aria-label="Menu lateral">
      <ul class="sidebar-links">
        <li><a href="index_files/Page375.htm">Organização</a></li>
        <li><a href="index_files/Page451.htm">Contactos</a></li>
        <li><a href="index_files/Page527.htm">Lista de serviços</a></li>
        <li><a href="index_files/Page618.htm">Lista de análises</a></li>
        <li><a href="index_files/Page700.htm">Lista de projectos</a></li>
        <li><a href="index_files/Page13415.htm">Colheitas</a></li>
        <li><a href="index_files/Page973.htm">Estudo Microbiológico</a></li>
        <li><a href="index_files/Page14388.htm">Métodos de análise</a></li>
      </ul>
    </aside>

    <article class="content" aria-labelledby="intro-title">
      <header class="content-header">
        <h1 id="intro-title">Serviço de Patologia Clínica — Centro Hospitalar e Universitário de Coimbra</h1>
      </header>

      <section class="hero" aria-hidden="false">
        <img src="index_files/image2364.png" alt="Cabeçalho do Serviço" class="hero-img">
      </section>

      <section class="intro">
        <p>
          O Serviço de Patologia Clínica do Centro Hospitalar e Universitário de Coimbra (CHUC) é um dos maiores Laboratórios Clínicos de Portugal,
          realizando uma ampla variedade de análises e serviços laboratoriais. Esta página reúne informação sobre organização, contactos,
          lista de serviços, análises, projectos e procedimentos de colheitas.
        </p>
        <p>
          As páginas internas (Organização, Contactos, Lista de análises, Colheitas, etc.) mantêm os ficheiros originais na pasta <code>index_files/</code>.
          Se encontrares caracteres estranhos noutros ficheiros, garante que os guardas em UTF-8.
        </p>
      </section>

      <section class="quick-links" aria-label="Acesso rápido">
        <h2>Acesso rápido</h2>
        <ul>
          <li><a href="index_files/Page618.htm">Lista de análises</a></li>
          <li><a href="index_files/Page13415.htm">Colheitas</a></li>
          <li><a href="index_files/Page973.htm">Estudo Microbiológico</a></li>
        </ul>
      </section>
    </article>
  </main>

  <footer class="site-footer" role="contentinfo">
    <div class="container">
      <p>© Centro Hospitalar e Universitário de Coimbra — Serviço de Patologia Clínica</p>
      <p><a href="index_files/Page451.htm">Contactos</a> | <a href="index_files/Page527.htm">Lista de serviços</a></p>
    </div>
  </footer>
</body>
</html>
HTML_EOF

          cat > styles.css <<'CSS_EOF'
:root{
  --bg:#ffffff;
  --text:#222;
  --accent:#ffc000;
  --muted:#666;
  --max-width:1100px;
  --gap:1rem;
  font-size:16px;
}

*{box-sizing:border-box}
html,body{height:100%}
body{
  margin:0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Trebuchet MS", Arial, sans-serif;
  color:var(--text);
  background:var(--bg);
  line-height:1.5;
}

/* Container */
.container{
  max-width:var(--max-width);
  margin:0 auto;
  padding:1rem;
}

/* Header */
.site-header{
  border-bottom:3px solid var(--accent);
  background:linear-gradient(180deg, #fff, #f8f8f8);
}
.header-inner{
  display:flex;
  align-items:center;
  justify-content:space-between;
  gap:var(--gap);
}
.logo img{display:block; height:auto; max-width:100%}
.main-nav ul{
  list-style:none;
  margin:0;
  padding:0;
  display:flex;
  gap:0.75rem;
  align-items:center;
}
.main-nav a{
  color:var(--text);
  text-decoration:none;
  padding:0.375rem 0.5rem;
}
.main-nav a:focus, .main-nav a:hover{
  outline:3px solid rgba(255,192,0,0.15);
  border-radius:4px;
}

/* Layout: sidebar + content */
.site-main{
  display:grid;
  grid-template-columns: 220px 1fr;
  gap:1.5rem;
  padding:1.25rem 1rem;
}
.sidebar{
  background:#fff;
  border:1px solid #eee;
  padding:0.5rem;
  border-radius:6px;
}
.sidebar-links{list-style:none;padding:0;margin:0}
.sidebar-links li{margin:0.25rem 0}
.sidebar-links a{color:var(--text); text-decoration:none}
.sidebar-links a:hover, .sidebar-links a:focus{color:var(--accent)}

/* Content */
.content{background:#fff;padding:1rem;border-radius:6px;border:1px solid #eee}
.content-header h1{margin:0 0 0.5rem 0;font-size:1.5rem}
.hero-img{width:100%;height:auto;display:block;margin:0 0 1rem 0}
.intro p{margin:0 0 1rem 0;color:var(--muted)}

/* Quick links */
.quick-links ul{list-style:disc;margin:0.5rem 0 0 1.25rem;padding:0}
.quick-links a{color:var(--text)}

/* Footer */
.site-footer{
  border-top:1px solid #eee;
  margin-top:2rem;
  padding:1rem 0;
  font-size:0.9rem;
  color:var(--muted);
}

/* Responsive */
@media (max-width:880px){
  .site-main{grid-template-columns:1fr; padding:0.5rem}
  .main-nav ul{flex-wrap:wrap; gap:0.5rem}
  .header-inner{padding:0.5rem 0}
  .sidebar{order:2}
  .content{order:1}
}
CSS_EOF

      - name: Create pull request with commit
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Convert index.htm to HTML5 and add styles.css (UTF-8)
          title: Convert index.htm to HTML5 + add styles.css
          body: |
            Converte index.htm (HTML gerado pelo Word) para HTML5, adiciona styles.css e define UTF-8. Mantém links para index_files/. Por favor valida as imagens e o encoding dos ficheiros em index_files/.
          base: ${{ github.event.repository.default_branch }}
          branch: convert/index-html5
          labels: automated
